all:
    children:
      sonatype-nexus:
        hosts:
          nexus:
            ansible_host: 0.0.0.0
            ansible_user: user
            ansible_port: 22
            ansible_become: true
