all:
    children:
      sonatype-nexus:
        hosts:
          nexus:
            ansible_host: 192.168.0.100
            ansible_user: ansible
            ansible_port: 22
            ansible_become: true
